import { defineConfig } from 'oxlint';

export default defineConfig({
  ignorePatterns: [
    '.agents/**',
    '.claude/**',
    '.cursor/**',
    'node_modules/**',
    'app/views/pwa/**',
    'public/vite/**',
    'public/vite-dev/**',
    'public/vite-test/**',
    'storybook-static/**',
    'tmp/**',
    'vendor/**',
    'tools/oxlint/anti-slop/**',
  ],
  plugins: ['typescript', 'unicorn', 'oxc', 'react', 'jsx-a11y', 'import', 'promise'],
  jsPlugins: [{ name: 'anti-slop', specifier: './tools/oxlint/anti-slop/index.ts' }],
  categories: {
    correctness: 'error',
    suspicious: 'error',
    perf: 'error',
  },
  rules: {
    'react/react-in-jsx-scope': 'off',
    'import/no-unassigned-import': 'off',

    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'warn',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
  },
});
