development:
  adapter: async

test:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "test") %>
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: cctv_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: cctv_production
